### ISSUE TITLE
OH，创世神，文件上传方式的断点 上传如何搞，还是要重写RequestBody,不确定的文件个数？如何添加呢

### ISSUE THREAD

**Issue by ailiboy520** [hongyangAndroid/okhttp-utils#100]

**Comment by hongyangAndroid** [comment]
针对文件上传的断点续传，单纯客户端这边是无法做到的，需要和服务器配合。

**Comment by hongyangAndroid** [comment]
这里有个参考[https://github.com/hongyangAndroid/okhttp-utils/issues/136](https://github.com/hongyangAndroid/okhttp-utils/issues/136)  不过肯定是需要服务器支持的，可以和该作者讨论，后续直接在#136下留言。
