### ISSUE TITLE
新版的okhttp-utils如何清除Cookie

### ISSUE THREAD

**Issue by hulegithub** [hongyangAndroid/okhttp-utils#102]
新版设置cookie
OkHttpClient.Builder okHttpClientBuilder = new OkHttpClient.Builder();
okHttpClientBuilder.cookieJar(new SimpleCookieJar());
请问我更换用户的时候如何清除cookie,框架里面有封装的方法吗？
我是在AS中直接 compile 'com.zhy:okhttputils:2.3.5'来引用你的utils的
求方法，在此不胜感激

**Comment by hongyangAndroid** [comment]
更新版本到：

```
compile 'com.zhy:okhttputils:2.3.7'
```

使用方法：

```
  OkHttpUtils.getInstance().getCookieStore().removeAll();
```

**Comment by hulegithub** [comment]
非常感谢
