### ISSUE TITLE
鸿洋，你自己试过吗？compile 'com.zhy:okhttputils:2.3.7'失败

### ISSUE THREAD

**Issue by qiujy** [hongyangAndroid/okhttp-utils#103]
Android Studio2.0Beta6，项目gradle文件中添加compile 'com.zhy:okhttputils:2.1.0'可以成功。但添加compile 'com.zhy:okhttputils:2.3.7' 就是失败。何解？？？

**Comment by qiujy** [comment]
更正一下：新建的项目添加就可以。老的项目，依赖包从2.1.0升级到2.3.7就不行。。

**Comment by onewilk** [comment]
翻墙就行了...我第一次也失败,翻墙再同步就搞定了...

**Comment by Ceprano** [comment]
我的在老工程里添加就不行，在新工程中就可以。不知道是不是冲突的问题
