### ISSUE TITLE
莫名会连续请求两次,请问有重试机制吗?

### ISSUE THREAD

**Issue by onewilk** [hongyangAndroid/okhttp-utils#104]
首先,我用的是post请求,异步....
然后,我这边检查代码中只调用了一次execute(),但是服务器告知我这边实际请求了两次,用Fiddler抓包看了下,确实请求了两次,第一次请求无result,body=-1,然后很快框架自动又发出了一次请求...后面这第二次请求有了正常的返回,请问框架的请求重试机制是在哪里,能否禁止重试?

**Comment by yanggming** [comment]
我也遇到了同样的情况

**Comment by hongyangAndroid** [comment]
默认的确有重试机制。可以通过`new OkHttpClient.Builder().retryOnConnectionFailure(false)`进行禁止。

**Comment by yanggming** [comment]
谢谢洋神


原始邮件
发件人:张鸿洋notifications@github.com
收件人:hongyangAndroid/okhttp-utilsokhttp-utils@noreply.github.com
抄送:yanggming372400028@qq.com; Commentcomment@noreply.github.com
发送时间:2016年4月22日(周五) 16:22
主题:Re: [hongyangAndroid/okhttp-utils] 莫名会连续请求两次,请问有重试机制吗? (#104)


Closed #104.
