### ISSUE TITLE
Https的下载报错

### ISSUE THREAD

**Issue by Gundam0079** [hongyangAndroid/okhttp-utils#109]
java.net.SocketTimeoutException: failed to connect to www.google.com/216.58.199.100 (port 443) after 10000ms
下载https开头的文件时 报SocketTimeoutException  
OkHttpUtils.getInstance().setCertificates();是默认的，不知和这个有关没有？

**Comment by onewilk** [comment]
你这是不翻墙连google吗?

**Comment by Gundam0079** [comment]
https://raw.githubusercontent.com/fengjundev/React-Native-Remote-Update/master/remote/index.android.bundle
这个网址不翻墙是可以打开的但是用工程下载就会报错
