### ISSUE TITLE
multi files

### ISSUE THREAD

**Issue by lh1241698502** [hongyangAndroid/okhttp-utils#111]
建议多图片上传时，增加多文件一起的方法，addFiles(List<FileInput> fileLists)
一个一个addFile不方便

**Comment by jinzw1993** [comment]
同感，大神加油。

**Comment by jinzw1993** [comment]
List<File>  files=new ArrayList<>();
            PostFormBuilder postFormBuilder=OkHttpUtils.post();
            for (File f:files){
                postFormBuilder.addFile("dsaf",f.getName(),f);

            }
            postFormBuilder.build().execute(new com.zhy.http.okhttp.callback.Callback() {
                @Override
                public Object parseNetworkResponse(Response response) throws Exception {
                    return null;
                }

                @Override
                public void onError(Call call, Exception e) {

                }

                @Override
                public void onResponse(Object o) {

                }
            });

这样写貌似就行，也挺方便。
