### ISSUE TITLE
上传文件的时候可以加上map参数，但是怎么加入json参数呢

### ISSUE THREAD

**Issue by zengcanxiang** [hongyangAndroid/okhttp-utils#113]
上传json到服务器，现在公布的应该是PostStringBuilder的content()方法。

但是上传文件的时候，用PostFormBuilder只可以带HashMap参数.
在实际使用场合，Android带json参数比较多的。没有找到方法可以带json参数。

并且，PostFileBuilder是不能带参数的。

**Comment by zengcanxiang** [comment]
@hongyangAndroid 鸿洋大神，我在寻找上面的解决方案的时候，找到了okhttp的分块请求，但是水平有限，无法集成到okhttpUtils里面，还请鸿洋大神加一下~

**Comment by hongyangAndroid** [comment]
目前封装的上传文件是POST FORM的方式，如果需要同时上传参考，只能通过键值对的方式，你可以讲你的json字符串作为参数的value传至后台。

对于你说的`okhttp的分块请求`，既上传文件有携带key-value的方式就属于分块请求。

对于你所说的既能携带文件，还能将json字符串可以requestBody的方式同时上传至服务器，我暂未发现任何方法。

**Comment by zengcanxiang** [comment]
额~~~ 我在一篇文章中找到一个这样的方法，是okhttp里面有：MultipartBuilder--------[连接](http://www.cnblogs.com/ct2011/p/3997368.html)

**Comment by hongyangAndroid** [comment]
对于你说的MultipartBuilder，就是okhttputils上传多问题的方案，实际上对应表单多文件上传+参数（key-value）。
```
 RequestBody requestBody = new MultipartBuilder()
        .type(MultipartBuilder.FORM)
        .addPart(
            Headers.of("Content-Disposition", "form-data; name=\"title\""),
            RequestBody.create(null, "Square Logo"))
        .addPart(
            Headers.of("Content-Disposition", "form-data; name=\"image\""),
            RequestBody.create(MEDIA_TYPE_PNG, new File("website/static/logo-square.png")))
        .build();
```
代码摘自你的链接，注意第一个为key为title,value为"Square Logo"，第二个key为image，值为一个图片文件。

并不支持将json字符串可以requestBody的方式同时上传至服务器，不过你可以通过文件上传json字符串，或者通过key-value的方式上传键值对。  这个key，在MultipartBuilder中是无法避免的。

**Comment by zengcanxiang** [comment]
原来如此,找到这个之后，我在网上搜寻过一些代码。

有一些Http响应体的内容，里面是通过一些乱码分割内容的，然后没有key1=xxx;key2=xxx这样的内容，我以为就是这个MultipartBuilder来生成乱码分割的。

让大神见笑了:)

**Comment by cervy** [comment]
这是我目前利用泛型封装的，可直接得到想要的类型



@Override
    public void onResponse(String response, int id) {
//        Log.e("server请求结果", response.toString());
        JSONTokener jsonParser = new JSONTokener(response);
        JSONObject httpdata = null;
        String data = null;
        try {
            httpdata = (JSONObject) jsonParser.nextValue();
            int code = httpdata.getInt("code");

            if (code != SF.ZERO) {
                Log.e("请求错误: " + code, SF.EMPTY);

                return;
            }
            data = httpdata.getString("data");
        } catch (JSONException e) {
            e.printStackTrace();

        }

        if (TextUtils.equals(data, SF.nulldata) || TextUtils.equals(data, "[]") || TextUtils.equals(data, "null") || TextUtils.isEmpty(data)) {
            Log.e("data为空哇", data);
            onNullData();
        } else {
            if (data.contains("[")) {
                onSuccesss(jsonToArrayList(data, getType()));
            } else {
                onSuccess(gson.fromJson(data, getType()));
            }


            Log.e("请求到的data", data);

        }
    }
