### ISSUE TITLE
不支持cache或者缓存有问题

### ISSUE THREAD

**Issue by zcwfeng** [hongyangAndroid/okhttp-utils#114]
当获取OkHttpClient 的时候因为单利，必须每次newBuilder() 才行，结果获取的对象不是同一个。
添加缓存根本就拿不到了。所以更改源码添加缓存代码，正在测试，不知道是否可以。

**Comment by hongyangAndroid** [comment]
```
OkHttpUtils.getInstance(
	new OkHttpClient.Builder().cache(new ...)...build();
	)
);
```
你可以将你构造好的okhttpclient对象，在Application中通过getInstance方式传入。
