### ISSUE TITLE
出错,已经没有那个api了,求完善

### ISSUE THREAD

**Issue by jackTang11** [hongyangAndroid/okhttp-utils#12]
<img width="735" alt="243cf93b-300a-4c62-8243-f50055798a0b" src="https://cloud.githubusercontent.com/assets/7345590/10503984/0b296af6-732e-11e5-89cc-7319de7d3a6b.png">
compileSdkVersion 23
    buildToolsVersion "23.0.1"

出错,已经没有那个api了

**Comment by hongyangAndroid** [comment]
重构了代码，已经更新依赖最新的okhttp版本。

**Comment by einice** [comment]
@jackTang11 这编辑器是啥主题配色啊？
