### ISSUE TITLE
在应用内怎么封装gson来解析response,只写一个callback

### ISSUE THREAD

**Issue by romantiskt** [hongyangAndroid/okhttp-utils#124]
如题,我看其它issuess内也有提到,自问自答,嘿嘿,可借鉴hongyang以前封装了gson的commit,
**1:自定义一个自己应用内的callback,**
`
  public abstract class MyCallBack<T> extends Callback<T> {
    public String resultString;
    Type mType;
    Gson mGson;

    public MyCallBack() {
        mType = getSuperclassTypeParameter(getClass());
        mGson=new Gson();
    }

    @Override
    public void onResponse(T response) {
        if (response instanceof Result) {
            int resultCode = ((Result) response).getResultCode();
            if (resultCode == 1) {
                responseSuccess(response);
            } else if (resultCode == Constants.TOKEN_FAILURE) {//token过期

            } else {
                responseException(response);
            }
        }
    }

    @Override
    public T parseNetworkResponse(Response response) throws IOException {
        resultString = response.body().string();
        return mGson.fromJson(resultString, mType);
    }

    static Type getSuperclassTypeParameter(Class<?> subclass) {
        Type superclass = subclass.getGenericSuperclass();
        if (superclass instanceof Class) {
            throw new RuntimeException("Missing type parameter.");
        }
        ParameterizedType parameterized = (ParameterizedType) superclass;
        return $Gson$Types.canonicalize(parameterized.getActualTypeArguments()[0]);
    }

    public abstract void responseSuccess(T response);

    public abstract void responseException(T response);
}`

** 2:自定义的bean,可根据服务器返回的结果提取出一个基本的result,如我们的就是下面这样视情况定,然后就是extends这个result啦,(/ □ \)...**
`public class Result {

    /**
     * resultCode : 1
     */

    private int resultCode;
    /**
     * detailMsg :
     * resultMsg : 手机号码已注册
     */

    private String detailMsg;
    private String resultMsg;

    public void setResultCode(int resultCode) {
        this.resultCode = resultCode;
    }

    public int getResultCode() {
        return resultCode;
    }

    public void setDetailMsg(String detailMsg) {
        this.detailMsg = detailMsg;
    }

    public void setResultMsg(String resultMsg) {
        this.resultMsg = resultMsg;
    }

    public String getDetailMsg() {
        return detailMsg;
    }

    public String getResultMsg() {
        return resultMsg;
    }
}`

**Comment by hongyangAndroid** [comment]
非常感谢，有类似提问会直接引用到issue。
