### ISSUE TITLE
关于持久Cookie存储PersistentCookieStore的问题

### ISSUE THREAD

**Issue by ihanbo** [hongyangAndroid/okhttp-utils#129]
难道没有人呢遇到这个问题吗？

` protected void add(HttpUrl uri, Cookie cookie)
    {
        String name = getCookieToken(cookie);

        // Save cookie into local store, or remove if expired
        if (!cookie.persistent())
        {
            if (!cookies.containsKey(uri.host()))
                cookies.put(uri.host(), new ConcurrentHashMap<String, Cookie>());
            cookies.get(uri.host()).put(name, cookie);
        } else
        {
            if (cookies.containsKey(uri.toString()))
                cookies.get(uri.host()).remove(name);
        }

        // Save cookie into persistent store
        SharedPreferences.Editor prefsWriter = cookiePrefs.edit();
        prefsWriter.putString(uri.host(), TextUtils.join(",", cookies.get(uri.host()).keySet()));
        prefsWriter.putString(COOKIE_NAME_PREFIX + name, encodeCookie(new SerializableHttpCookie(cookie)));
        prefsWriter.commit();
    }`

其中添加Cookie判断方面 是不是方法搞错了？ ` if (!cookie.persistent()) `是：假如cookie不是持久化的话 添加cookie，因为这个判断 导致添加不了cookie，这里应该是：假如cookie没有过期的话 添加cookie。应该改成 `if (cookie.expiresAt() > System.currentTimeMillis())`

还有个问题，假如cookie的domain为.开头的话，如 `domain=.ycapp.yiche.com` 的话Okhttp 处理cookie时会把点去掉，参考 okhttp3.Cookie#parseDomain 方法。这种怎么解决？

**Comment by hongyangAndroid** [comment]
多谢提出，关于PersistentCookieStore 代码已经作了部分修改，可以参考[#issue137](https://github.com/hongyangAndroid/okhttp-utils/issues/137)

**Comment by jiaowenzheng** [comment]
https://segmentfault.com/a/1190000004345545  这个完美解决！
