### ISSUE TITLE
https双向认证，为什么只用了client.bks?

### ISSUE THREAD

**Issue by chaozaiai** [hongyangAndroid/okhttp-utils#132]
http://blog.csdn.net/lmj623565791/article/details/48129405
你这里的双向认证，代码里只是用到了客户端的bks。
使用volley的时候，创建SSLSocketFactory 使用到了客户端和server端两个bks。
为什么你这里只有一个呢？

**Comment by hongyangAndroid** [comment]
代码里面也是两个呀，一个cer,一个bks 。
>首先对于双向证书验证，也就是说，客户端也会有个“kjs文件”，服务器那边会同时有个“cer文件”与之对应。
我们已经生成了zhy_server.kjs和zhy_server.cer文件。
接下来按照生成证书的方式，再生成一对这样的文件，我们命名为:zhy_client.kjs,zhy_client.cer.

一个两对，每端两个。

你可以仔细阅读下博客。

**Comment by chaozaiai** [comment]
又细细看了一遍，果然。
server证书是在application通过setCertificates传进来的，client证书是在setCertificates里面。两个分开了。
大意了，谢谢呀。
