### ISSUE TITLE
关于PersistentCookieStore请教下洋神

### ISSUE THREAD

**Issue by tankai2525** [hongyangAndroid/okhttp-utils#137]
开始看到这个类，我好开心。我以为直接用他重新初始化OkHttpClient，后来发现不行
// Save cookie into local store, or remove if expired
        if (!cookie.persistent()) 
        {
            if (!cookies.containsKey(uri.host()))
                cookies.put(uri.host(), new ConcurrentHashMap<String, Cookie>());
            cookies.get(uri.host()).put(name, cookie);
        } else
        {
            if (cookies.containsKey(uri.toString()))
                cookies.get(uri.host()).remove(name);
        }

我在登陆完成后，看了下我cookie的 persistent 为true,尼玛 为true不就代表会话结束后过期。
Set-Cookie: xxx_auth=0804yYSmNXz%2FBmS54SLSAc%2FvyEmSGM0rd%2F7Lo%2Fhq9SCtD1GSQqCLG5MANlWL7g; expires=Thu, 12-May-2016 11:24:37 GMT; Max-Age=2592000; path=/; domain=.xxxcom

我就是想问下 persistent为啥是true 而不是false.  谢谢

**Comment by hongyangAndroid** [comment]
简单修改了下PersistentCookieStore的逻辑，欢迎测试~
也可以尝试自定义实现CookieStore，此外还可以参考该库[https://github.com/franmontiel/PersistentCookieJar](https://github.com/franmontiel/PersistentCookieJar)
