### ISSUE TITLE
如何做cookie的永久性保存呢？

### ISSUE THREAD

**Issue by MarnonLee** [hongyangAndroid/okhttp-utils#142]
想问一下这个okhttp - util怎么才能做永久的cookie保存呢？现在虽然保存session了，但是重启app就又没有了，但是我们做登陆需要保存这个字段一段时间，调用那个方法可以获取到初次访问时候返回的cookie呢

**Comment by hongyangAndroid** [comment]
默认cookie存储在内存中，可以通过`OkHttpUtils.getInstance().getCookieStore().get(uri)`获取cookies.

**Comment by squery** [comment]
我是这样获取的
` public static String getCookieValue() {
        String s = null;
        List<Cookie> cookies = OkHttpUtils.getInstance().getCookieStore().getCookies();
        if (cookies != null) {
            for (Cookie httpCookie : cookies) {
                if ("xtrdobd".equals(httpCookie.name())) {
                    s = httpCookie.name() + "=" + httpCookie.value();
                }
            }
        }
        if (s != null) {
            PreferenceSettingUtils.setCookie(InsProxyApp.getAppContext(), s);
        }
        return s;
    }`
