### ISSUE TITLE
鸿洋大神你好，我想给这个Utils添加支持Activity和Fragment生命周期结束后终止请求

### ISSUE THREAD

**Issue by zlwer** [hongyangAndroid/okhttp-utils#143]
您有什么好的思路或者意见和建议没有？

**Comment by BrightYu** [comment]
![image](https://cloud.githubusercontent.com/assets/5258055/14634063/e6e0dd6a-0652-11e6-8fb0-98d7de1bcb66.png)
已经有的

**Comment by zlwer** [comment]
- - 没好好看文档。谢谢啊~
