### ISSUE TITLE
莫名发送两个请求

### ISSUE THREAD

**Issue by yanggming** [hongyangAndroid/okhttp-utils#146]
网络不佳的时候，抓包看到发送了两个请求。请问是洋神加的机制还是okhttp自带的？

**Comment by act262** [comment]
这个时okhttp重试机制，网络不佳时会重试请求，可以设置关闭重试请求

**Comment by hongyangAndroid** [comment]
thx @act262 我没有添加这个机制，应该是okhttp自带的。
