### ISSUE TITLE
携带的参数只支持String类型吗

### ISSUE THREAD

**Issue by romantiskt** [hongyangAndroid/okhttp-utils#148]
不能携带 double 这些其它类型

**Comment by hongyangAndroid** [comment]
你可以把double转成字符串。

**Comment by romantiskt** [comment]
有时候服务器没有这么好沟通,别人就是要double类型的,,,(/ □ \)

**Comment by hongyangAndroid** [comment]
http协议中就没有传递double类型这一说，服务器如果说要double类型，你将double转化为字符串传过去肯定没问题。 

这样的服务器一般都是使用了一些框架，其实转化的操作是服务器那边控制层框架完成的，你只要保证你传过去的数据可以正常转化为double即可。

**Comment by romantiskt** [comment]
ok,受教了,谢谢(*^__^*)
