### ISSUE TITLE
如何清除cookie

### ISSUE THREAD

**Issue by hulegithub** [hongyangAndroid/okhttp-utils#15]
你在构造器这里使用cookie，我要怎么写才能清除cookie，比如我现在用A账户登录，设置cookie，再换成B用户登录，结果请求的数据还是A账户的，要怎么实现清除cookie，求指导
private OkHttpClientManager()
    {
        mOkHttpClient = new OkHttpClient();
        //cookie enabled
        mOkHttpClient.setCookieHandler(new CookieManager(null, CookiePolicy.ACCEPT_ALL));
        mDelivery = new Handler(Looper.getMainLooper());
        mGson = new Gson();

        /*just for test !!!*/
        mOkHttpClient.setHostnameVerifier(new HostnameVerifier()
        {
            @Override
            public boolean verify(String hostname, SSLSession session)
            {
                return true;
            }
        });

    }

**Comment by hongyangAndroid** [comment]
将上面的CookieManager保存为成员变量，例如：mCookieManager,当需要清楚cookie的时候调用：

```java
mCookieManager.getCookieStore().remove()/removeAll();
```
