### ISSUE TITLE
OkHttp打印request问题

### ISSUE THREAD

**Issue by squery** [hongyangAndroid/okhttp-utils#151]
在你之前的版本打印request的具体信息  ，我记得是在你自定义的额抽象的 OkHttpRequest类中的构造方法中，直接 OkHttpRequest.toString();
但是现在你修改了后，添加了LoggerInterceptor 我这边根本不生效。  为了避免去下载你的库，去修改代码的情况下   我做了如下几个尝试 1.在OkhttpUtils中的exceute（）中根据 callBack拿到requset
2.  在onBefore（request）中取到request     3.在parseNetworkResponse（response）中通过respone取得request。  这几个方法   都不可行。  请问  这个问题该如何解决。

**Comment by hongyangAndroid** [comment]
目前版本支持通过` OkHttpUtils.getInstance().debug("testDebug");`开启日志。

对于以前的版本，你可以自行设置添加`Interceptor `例如`LoggerInterceptor`来输出日志。

也可以参考官方给出的log模块，[https://github.com/square/okhttp/tree/master/okhttp-logging-interceptor](https://github.com/square/okhttp/tree/master/okhttp-logging-interceptor)

**Comment by squery** [comment]
您好，楼主是这样的，我为了延续之前的版本  我是在OkhttpRequest中添加了 ,但是这样就导致我 要把你的库down下来然后再去修改这个类  我没办法去继承这个类，因为这个类 好多地方都在被重用。
```
 L.e(this.toString());
 protected OkHttpRequest(String url, Object tag,
                            Map<String, String> params, Map<String, String> headers)
    {
        this.url = url;
        this.tag = tag;
        this.params = params;
        this.headers = headers;

        if (url == null)
        {
            Exceptions.illegalArgument("url can not be null.");
        }

        initBuilder();

        L.e(this.toString());
    }
 @Override
    public String toString()
    {
        return "OkHttpRequest{" +
                "url='" + url + '\'' +
                ", tag=" + tag +
                ", params=" + params +
                ", headers=" + headers +
                '}';
    }
```

**Comment by squery** [comment]
楼主你给的这个
'com.squareup.okhttp3:logging-interceptor:(insert latest version)'  无法添加依赖
你自己提供的那个OkHttpUtils.getInstance().debug("testDebug");  也就是getOkHttpClient().newBuilder().addInterceptor(new LoggerInterceptor(tag, false)).build();  无法打印request中的提交的请求参数
