### ISSUE TITLE
Okhttp中的PostFromBuilder

### ISSUE THREAD

**Issue by squery** [hongyangAndroid/okhttp-utils#152]
这个类  在你之前的额版本中存在的问题就是 当 上传文件到服务器时  如果一个key  对应多个文件  也就是一个key 对应一个map<String, File>. 在这个版本中得到了修改。
但是 在上个版本的时候  存在一个files(Map<String,File> map)，但是在这个版本 中只有addFile（Sting File），如果有好多个文件上传的时候  ，为了避免一直addFile    所以我认为  添加一个方法   files  ，

为了解决这些问题  我自定义了OkhttpUtils  和 PostFromBuilder。以解决问题。

关键是  request日志的打印问题。

**Comment by hongyangAndroid** [comment]
`compile 'com.zhy:okhttputils:2.4.1'`

通过files(String key, Map<String, File> files)方法设置多文件。


示例：

```
OkHttpUtils.post()//
    .files("key", map)//
    .url(url)
    .params(params)//
    .headers(headers)//
    .build()//
    .execute(new MyStringCallback());
```
