### ISSUE TITLE
请问如何打印请求的Params参数，记得之前是有的

### ISSUE THREAD

**Issue by chengxianliang** [hongyangAndroid/okhttp-utils#153]
如题，现在打印的是红色的字体

如：
04-25 09:58:56.252 9926-15322/com. E/net: ========response'log=======
04-25 09:58:56.252 9926-15322/com.
 E/net: url : http://api.。。。。
04-25 09:58:56.252 9926-15322/com. E/net: code : 200
04-25 09:58:56.252 9926-15322/com. E/net: protocol : http/1.1
04-25 09:58:56.252 9926-15322/com. E/net: message : OK
04-25 09:58:56.252 9926-15322/com. E/net: ========response'log=======end
requestBody's contentType : application/x-www-form-urlencoded
E/Debug: requestBody's content :  maybe [file part] , too large too print , ignored!
 E/Debug: ========request'log=======end

我想像以前一样，可以打印请求的params，可以方便调试

**Comment by hongyangAndroid** [comment]
自定通过okhttpclient#addInterceptor的方式进行添加。
