### ISSUE TITLE
参数问题

### ISSUE THREAD

**Issue by colinnj** [hongyangAndroid/okhttp-utils#157]
请问OkHttpUtils中post时的addParams方法是只能为String、String吗？如果遇到传对象的怎么办？

**Comment by hongyangAndroid** [comment]
参考  #148

**Comment by colinnj** [comment]
谢谢，我遇到的情况为可能需要传一个javabean进去。后来我使用OkHttpUtils.postString()这个完成请求的。把使用方法分享出来，OkHttpUtils.postString().url("您的URL").content(利用new Gson().toJson()方法把javabean对象转换成json字符串).mediaType(MediaType.parse("application/json; charset=utf-8")).build().execute()
