### ISSUE TITLE
报错 java.lang.ArrayIndexOutOfBoundsException: length=12; index=-1，java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String okhttp3.Cookie.name()' on a null object reference

### ISSUE THREAD

**Issue by KinaZhen** [hongyangAndroid/okhttp-utils#159]
最新AndroidStudio  instance run 运行应用 就会报如下错误：
java.lang.ArrayIndexOutOfBoundsException: src.length=1 srcPos=0 dst.length=12 dstPos=-1 length=1
04-27 13:33:39.390 30219-30426/ W/System.err:     at java.lang.System.arraycopy(Native Method)
04-27 13:33:39.400 30219-30426/ W/System.err:     at java.util.ArrayList.addAll(ArrayList.java:202)
04-27 13:33:39.400 30219-30291/ I/System.out: close [socket][/0.0.0.0:50770]
04-27 13:33:39.400 30219-30426/ W/System.err:     at com.zhy.http.okhttp.cookie.store.MemoryCookieStore.add(MemoryCookieStore.java:35)
04-27 13:33:39.400 30219-30426/ W/System.err:     at com.zhy.http.okhttp.cookie.CookieJarImpl.saveFromResponse(CookieJarImpl.java:29)
04-27 13:33:39.400 30219-30426/ W/System.err:     at okhttp3.internal.http.HttpEngine.receiveHeaders(HttpEngine.java:866)
04-27 13:33:39.400 30219-30426/ W/System.err:     at okhttp3.internal.http.HttpEngine.readResponse(HttpEngine.java:598)
04-27 13:33:39.400 30219-30426/ W/System.err:     at okhttp3.RealCall.getResponse(RealCall.java:241)
04-27 13:33:39.400 30219-30426/ W/System.err:     at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:198)
04-27 13:33:39.400 30219-30426/ W/System.err:     at com.zhy.http.okhttp.log.LoggerInterceptor.intercept(LoggerInterceptor.java:46)
04-27 13:33:39.400 30219-30426/ W/System.err:     at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:187)
04-27 13:33:39.400 30219-30426/ W/System.err:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:160)
04-27 13:33:39.400 30219-30426/ W/System.err:     at okhttp3.RealCall.access$100(RealCall.java:30)
04-27 13:33:39.400 30219-30426/ W/System.err:     at okhttp3.RealCall$AsyncCall.execute(RealCall.java:127)
04-27 13:33:39.400 30219-30426/ W/System.err:     at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
04-27 13:33:39.400 30219-30426/ W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
04-27 13:33:39.400 30219-30426/ W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
04-27 13:33:39.400 30219-30426/ W/System.err:     at java.lang.Thread.run(Thread.java:831)
04-27 13:33:39.400 30219-30291/ W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String okhttp3.Cookie.name()' on a null object reference
04-27 13:33:39.400 30219-30291/ W/System.err:     at com.zhy.http.okhttp.cookie.store.MemoryCookieStore.add(MemoryCookieStore.java:28)
04-27 13:33:39.400 30219-30291/ W/System.err:     at com.zhy.http.okhttp.cookie.CookieJarImpl.saveFromResponse(CookieJarImpl.java:29)
04-27 13:33:39.400 30219-30291/ W/System.err:     at okhttp3.internal.http.HttpEngine.receiveHeaders(HttpEngine.java:866)
04-27 13:33:39.400 30219-30291/ W/System.err:     at okhttp3.internal.http.HttpEngine.readResponse(HttpEngine.java:598)
04-27 13:33:39.400 30219-30291/ W/System.err:     at okhttp3.RealCall.getResponse(RealCall.java:241)
04-27 13:33:39.400 30219-30291/ W/System.err:     at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:198)
04-27 13:33:39.400 30219-30291/ W/System.err:     at com.zhy.http.okhttp.log.LoggerInterceptor.intercept(LoggerInterceptor.java:46)
04-27 13:33:39.400 30219-30291/ W/System.err:     at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:187)
04-27 13:33:39.400 30219-30291/ W/System.err:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:160)
04-27 13:33:39.400 30219-30291/ W/System.err:     at okhttp3.RealCall.access$100(RealCall.java:30)
04-27 13:33:39.400 30219-30291/ W/System.err:     at okhttp3.RealCall$AsyncCall.execute(RealCall.java:127)
04-27 13:33:39.400 30219-30291/ W/System.err:     at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
04-27 13:33:39.400 30219-30291/ W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
04-27 13:33:39.400 30219-30291/ W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
04-27 13:33:39.400 30219-30291/ W/System.err:     at java.lang.Thread.run(Thread.java:831)

**Comment by hongyangAndroid** [comment]
问题已经尝试修复，请使用:
```
	compile 'com.zhy:okhttputils:2.4.1'
```
