### ISSUE TITLE
登录的Cookie跟请求其他链接时的Cookie不一致

### ISSUE THREAD

**Issue by hexianqiao3755** [hongyangAndroid/okhttp-utils#164]
已经登录的情况下,请求数据时候的Cookie为什么跟登录后给的Cookie不是同一个,, 导致了获取不到数据

**Comment by hongyangAndroid** [comment]
需要自行设置cookie.

对于cookie，直接通过cookiejar方法配置.

```
CookieJarImpl cookieJar = new CookieJarImpl(new PersistentCookieStore(getApplicationContext()));
OkHttpClient okHttpClient = new OkHttpClient.Builder()
          .cookieJar(cookieJar)
          //其他配置
         .build();
                 
OkHttpUtils.initClient(okHttpClient);
```
目前项目中包含：

* PersistentCookieStore //持久化cookie
* SerializableHttpCookie //持久化cookie
* MemoryCookieStore //cookie信息存在内存中

如果遇到问题，欢迎反馈，当然也可以自己实现CookieJar接口，编写cookie管理相关代码。

此外，对于持久化cookie还可以使用[https://github.com/franmontiel/PersistentCookieJar](https://github.com/franmontiel/PersistentCookieJar).

相当于框架中只是提供了几个实现类，你可以自行定制或者选择使用。
