### ISSUE TITLE
文件上传bug

### ISSUE THREAD

**Issue by jtyang** [hongyangAndroid/okhttp-utils#17]
洋神，新版本的文件上传request代码有个bug：
OkHttpPostRequest 的构造方法，会校验参数，但是文件上传的时候，Uploadrequest构造参数中super方法传的file字段却是null，导致参数校验不通过。

**Comment by hongyangAndroid** [comment]
多谢反馈，已经修复。

**Comment by oilyu** [comment]
没有修复吧？我在文件上传时，构建Uploadrequest只传入了files，没有传params还是会报错

**Comment by hongyangAndroid** [comment]
ok，再试试~~
