### ISSUE TITLE
为什么Cookie带不到服务器去.....有什么办法手动带吗

### ISSUE THREAD

**Issue by hexianqiao3755** [hongyangAndroid/okhttp-utils#170]

**Comment by squery** [comment]
直接加header  
 public static <T> void getForObject(final Context activity, String url, final Class<T> className,
                                        final NetSucessCallBack<T> callBack) {
        OkHttpUtils.makeGetRequestBuilder()
                .addHeader("Cookie", PreferenceSettingUtils.getCookie(activity))
                .url(url)
                .build()
                .execute(new OkhttpCallbackImpl.OkhttpBuilder<T>(activity, className)
                        .setterSucessCallBackForObjcet(callBack)
                        .build()
                );
    }

**Comment by hongyangAndroid** [comment]
目前更新了版本至2.5.1，详细可看readme。
对于cookie，直接通过cookiejar方法配置，参考上面的配置过程。

```
CookieJarImpl cookieJar = new CookieJarImpl(new PersistentCookieStore(getApplicationContext()));
OkHttpClient okHttpClient = new OkHttpClient.Builder()
          .cookieJar(cookieJar)
          //其他配置
         .build();
                 
OkHttpUtils.initClient(okHttpClient);
```
目前项目中包含：

* PersistentCookieStore //持久化cookie
* SerializableHttpCookie //持久化cookie
* MemoryCookieStore //cookie信息存在内存中

如果遇到问题，欢迎反馈，当然也可以自己实现CookieJar接口，编写cookie管理相关代码。

此外，对于持久化cookie还可以使用[https://github.com/franmontiel/PersistentCookieJar](https://github.com/franmontiel/PersistentCookieJar).

相当于框架中只是提供了几个实现类，你可以自行定制或者选择使用。
