### ISSUE TITLE
手机网络关掉以后，请求不会走onError

### ISSUE THREAD

**Issue by android-xiaowei** [hongyangAndroid/okhttp-utils#171]
手机网络关掉以后，请求不会走onError

**Comment by squery** [comment]
你确定是没进入onerror，你打个log看看，你可以这样处理啊。
  if (status > 200 && status < 600) {// http连接中的状态码 200到600之间，认为是服务器错误
            AppUtils.getInstance().showDialog(activity, Constant.ResponseError);
        } else {
            switch (status) {
                case 200:// 成功的时候，极有可能是解析出现的异常
                    AppUtils.getInstance().showDialog(activity, Constant.ParseError);
                    break;
                case 0:// 失败的时候  eg：网络原因 导致的读写超时、连接超时、 以及没有网络的情况下
                    if (!DeviceUtils.IsNetworkAvailable()) {
                        AppUtils.getInstance().showDialog(activity, Constant.CheckNet);
                    } else {
                        AppUtils.getInstance().showDialog(activity, Constant.NetQuestion);
                    }
                    break;
                default:// -1的时候,属于未知异常  这里有待完善和修改。。。。极少发生
                    ToastUtils.toastShort(Constant.UnKnownException);
                    break;
            }
        }

在onError中调用 case0就好

**Comment by android-xiaowei** [comment]
没有走，有log的

**Comment by android-xiaowei** [comment]
requestCall.getCall().enqueue(new okhttp3.Callback() {
            @Override
            public void onFailure(Call call, IOException e) {
                sendFailResultCallback(call, e, finalCallback);
            }

            @Override
            public void onResponse(Call call, Response response) {
                if (response.code() >= 400 && response.code() <= 599) {
                    sendFailResultCallback(call, new RuntimeException("The Response code is " + response.code()), finalCallback);
                    return;
                }

                try {
                    Object o = finalCallback.parseNetworkResponse(response);
                    sendSuccessResultCallback(o, finalCallback);
                } catch (Exception e) {
                    sendFailResultCallback(call, e, finalCallback);

                }

            }
        });
没有网络的时候会直接走onFailure，但是没回调onError
