### ISSUE TITLE
希望可以在Callback的onBefore方法中检测网络连接，如果没网络就不执行请求

### ISSUE THREAD

**Issue by nicegoing** [hongyangAndroid/okhttp-utils#172]
很多时候都需要先检测网络，再发起请求。希望Callback的onBefore方法返回值为boolean.当没有网络时，不执行请求。
`

    public void execute(Callback callback)

    {

        buildCall(callback);
        if (callback != null)
        {
            callback.onBefore(request);
           //这里增加boolean值判断，如果返回false，就直接return.
        }

        OkHttpUtils.getInstance().execute(this, callback);
    }

`

**Comment by hongyangAndroid** [comment]
多谢提意见，需要考虑下~
