### ISSUE TITLE
请大神看看PersistentCookieStore中add方法还是有问题

### ISSUE THREAD

**Issue by zcycn** [hongyangAndroid/okhttp-utils#179]
`if (cookie.persistent())
        {
            if (!cookies.containsKey(uri.host()))
                cookies.put(uri.host(), new ConcurrentHashMap<String, Cookie>());
            cookies.get(uri.host()).put(name, cookie);
        }`
上面首次访问网络并无法执行，导致
cookies.get(uri.host()).keySet()空指针

改为如下代码能够正常缓存cookie
`if (!cookie.persistent()) {
            if (!cookies.containsKey(uri.host())) {
                cookies.put(uri.host(), new ConcurrentHashMap<String, Cookie>());
            }
            cookies.get(uri.host()).put(name, cookie);
        } else {
            if (cookies.containsKey(uri.host())) {
                cookies.get(uri.host()).remove(name);
            }
        }`

**Comment by 1040087877** [comment]
我也是这个地方报错，不过用studio为什么改不了源码，我想测试下

**Comment by zcycn** [comment]
@1040087877 可以下载到本地以Library使用形式导入到项目中。修改后我测试是没问题的。

**Comment by 1040087877** [comment]
好的 谢谢

**Comment by 1040087877** [comment]
确实是个bug，我用了你那代码后真的成功了，真的谢谢你，我这几天调式了很久，还以为是我代码问题，thankyou。

**Comment by hongyangAndroid** [comment]
多谢以上各位，已经按照上述修改。并且考虑扩展性，做了如下修改：

对于cookie，直接通过cookiejar方法配置，参考上面的配置过程。

```
#Application的onCreate中
CookieJarImpl cookieJar = new CookieJarImpl(new PersistentCookieStore(getApplicationContext()));
OkHttpClient okHttpClient = new OkHttpClient.Builder()
          .cookieJar(cookieJar)
          //其他配置
         .build();
                 
OkHttpUtils.initClient(okHttpClient);
```
目前项目中包含：

* PersistentCookieStore //持久化cookie
* SerializableHttpCookie //持久化cookie
* MemoryCookieStore //cookie信息存在内存中

此外，对于持久化cookie还可以使用[https://github.com/franmontiel/PersistentCookieJar](https://github.com/franmontiel/PersistentCookieJar).

相当于框架中只是提供了几个实现类，你可以自行定制或者选择使用。
