### ISSUE TITLE
有没有代码混淆的时候出问题的

### ISSUE THREAD

**Issue by yilylong** [hongyangAndroid/okhttp-utils#18]
没有混淆前正常。混淆后运行报错
---
![](https://raw.githubusercontent.com/yilylong/ImageResource/master/error.png)
已经将okhttp 和 鸿洋的工具库都 keep 了 是哪里没有keep 到呢 调用的就是简单的一个get请求返回String 
--
-dontwarn com.squareup.okhttp.**
-keep class com.squareup.okhttp.**{*;}
-keep class com.zhy.http.okhttp.**{*;}
-keep class com.google.gson.** {*;}
-keep class com.google.gson.JsonObject { *; }

好像这个方法抛出的

    static Type getSuperclassTypeParameter(Class<?> subclass)
    {
        Type superclass = subclass.getGenericSuperclass();
        if (superclass instanceof Class)
        {
            throw new RuntimeException("Missing type parameter.");
        }
        ParameterizedType parameterized = (ParameterizedType) superclass;
        return $Gson$Types.canonicalize(parameterized.getActualTypeArguments()[0]);
    }

**Comment by cxbiao** [comment]
请禁止优化泛型,-keepattributes Signature

**Comment by yilylong** [comment]
@cxbiao 谢谢 解决了
