### ISSUE TITLE
GetBuilder类中方法appendParams应该判断一下url中是否已经有"?"的情况。

### ISSUE THREAD

**Issue by jackzhonglyy** [hongyangAndroid/okhttp-utils#198]
protected String appendParams(String url, Map<String, String> params)
{
    StringBuilder sb = new StringBuilder();
    **_sb.append(url + "?");_**
    if (params != null && !params.isEmpty())
    {
        for (String key : params.keySet())
        {
            sb.append(key).append("=").append(params.get(key)).append("&");
        }
    }
    sb = sb.deleteCharAt(sb.length() - 1);
    return sb.toString();
}

**Comment by jackzhonglyy** [comment]
url += url.contains("?") ? "&" : "?";
sb.append(url);

**Comment by hongyangAndroid** [comment]
#182  已经合并pr。
