### ISSUE TITLE
部分酷派手机使用OKHTTP偶尔获取不到数据的问题

### ISSUE THREAD

**Issue by Saxxhw** [hongyangAndroid/okhttp-utils#2]
洋神你好！前一段时间考虑过使用okhttp作为网络请求框架，测试时发现在酷派大神F1手机(刷的MIUI5.0)上经常获取数据失败，也在网上查了些相关资料，不知道现在还有没有这个问题？求大神抽时间解答。。拜谢

**Comment by hongyangAndroid** [comment]
貌似之前的版本有这样的问题，据说在2.4的时候会修复，现在已经2.5.0了。如果你有酷派手机，可以测试下~~~欢迎回复测试结果。

**Comment by androidxu** [comment]
我想知道后续怎么样了，酷派手机现在用okhttp的话，还有问题吗？求知道的解答下，谢谢！

**Comment by aikongmeng** [comment]
我也想知道現在酷pai行不行

**Comment by Saxxhw** [comment]
现在已经可以了，使用okhttp的最新jar包。

**Comment by ChoicesWang** [comment]
我前几天看了okhttp的issue。他们说这个bug是又两个问题引起的。已经改好了其中一个，另一个还没有改。

**Comment by longtaoge** [comment]
这个，倒底敢不敢用

**Comment by Saxxhw** [comment]
可以用的，我现在公司项目就在使用okhttp，目前还没有出现过获取不到数据的问题。已经很稳定了，就算是Google的api也不敢保证任何情况都完美处理吧。
