### ISSUE TITLE
中文乱码怎么解决!?

### ISSUE THREAD

**Issue by zhougonglai** [hongyangAndroid/okhttp-utils#200]
所有的中文都变成了???怎么解决?
同一个接口前端的返回是正常的:
<code>
[{"id":"1000000","name":"北京","shortName":"BJ","type":"1"},{"id": ....
</code>
OKHttp返回的却是:
<code>
[{"id":"1000000","name":"???","shortName":"BJ","type":"1"},{"id":....
</code>
另:
我用:
<code>
                header.put("Content-Type","application/json;charset=UTF-8");
                OkHttpUtils.get().headers(header)
</code>
也没效果

**Comment by hongyangAndroid** [comment]
有没有接口地址？

**Comment by zhougonglai** [comment]
http://www.yifudai.com/wechat/getCity

**Comment by hongyangAndroid** [comment]
你这浏览器直接访问都是乱码哇

<img width="857" alt="2016-05-24 3 19 43" src="https://cloud.githubusercontent.com/assets/10704521/15495544/340d9c28-21c3-11e6-90b8-33e03329da02.png">

**Comment by zhougonglai** [comment]
这个....公司给的接口..( ⊙ o ⊙ )啊！打扰了
