### ISSUE TITLE
鸿大哥，基于POST的文件上传（类似web上的表单），我用的files，我传了五张图片，但是最后服务端只接收了一张，这是怎么回事，是不是类别表单中<input type="file" name="mFile"/>的name属性有关？

### ISSUE THREAD

**Issue by shisp** [hongyangAndroid/okhttp-utils#204]
HashMap<String, Object> paramMap = new HashMap<String, Object>();
paramMap.clear();
				paramMap.put("post_title", "OkHttpFiles");//故事标题
				paramMap.put("category_id", 0);//分类id：全部=0；小发现=1；大吃货=2；高颜值=3；近郊游=4；灌水区=5
				File imageDir = Environment.getExternalStorageDirectory();
				File file1 = new File(imageDir + "/yunposningde/splashImage.png");
				File file2 = new File(imageDir + "/yunposningde/lotteryMainBgImage.png");
				File file3 = new File(imageDir + "/yunposningde/splashImage.png");
				File file4 = new File(imageDir + "/yunposningde/lotteryMainBgImage.png");
				File file5 = new File(imageDir + "/yunposningde/splashImage.png");
				Map<String, File> fileMap = new HashMap<String, File>();
				fileMap.put("splashImage.png", file1);
				fileMap.put("lotteryMainBgImage.png", file2);
				fileMap.put("splashImage3.png", file3);
				fileMap.put("splashImage4.png", file4);
				fileMap.put("splashImage5.png", file5);
				OkHttpUtils
					.post()
					.url(YunposRestClient.getAbsoluteUrl(ServiceInterface.addstorypost))
					.files("file", fileMap)
					.params(ParamUtil.requestParamsMap(paramMap))
					.build()
					.execute(new Callback<String>() {
						
						@Override
						public void onResponse(String arg0) {
							// TODO Auto-generated method stub
							if(!TextUtils.isEmpty(arg0)){
								arg0 = ParamUtil.unicodeToChinese(arg0);
							}
							Toast.makeText(getApplicationContext(), "post5_btn onResponse = " + arg0, Toast.LENGTH_LONG).show();
						}
						
						@Override
						public void onError(Call arg0, Exception arg1) {
							// TODO Auto-generated method stub
							Toast.makeText(getApplicationContext(), "post5_btn onError = " + arg1, Toast.LENGTH_LONG).show();
						}

						@Override
						public String parseNetworkResponse(Response arg0)
								throws Exception {
							// TODO Auto-generated method stub
							return arg0.body().string();
						}

						@Override
						public void inProgress(float progress) {
							// TODO Auto-generated method stub
							Log.e("inProgress progress = ", "" + progress);
							super.inProgress(progress);
						}						
						
					});

**Comment by hongyangAndroid** [comment]
```
<input type="file" name="mFile"/>
```
这个对应应该

```
.files("mFile", fileMap)//第一个参数和上面的name对应
```
ps:服务器那边应该是文件数组接收。

**Comment by shisp** [comment]
谢谢，鸿大哥
