### ISSUE TITLE
请教：post上传图片成功还是error：404

### ISSUE THREAD

**Issue by JerryJson** [hongyangAndroid/okhttp-utils#208]
如题，这是什么原因啊

**Comment by hongyangAndroid** [comment]
需要详细的描述。

**Comment by JerryJson** [comment]
接口是这样的
`File file = new File(Environment.getExternalStorageDirectory(), "123456.jpg");

        Log.i("test", "uploadFile: filePath  " + file.getAbsolutePath());
        Log.i("test", "uploadFile: length  " + file.length());

        if (!file.exists()) {
            Log.i("test", "uploadFile: error ");
            return;
        }
        Map<String, String> params = new HashMap<>();
        params.put("functionId", "testFile");
        params.put("fileType", ".jpg");
        params.put("maxSize", file.length() + "");


        OkHttpUtils.post()
                .addFile("myfiles", "123465.jpg", file)//
                .url(API.HOST + methodName)//
                .params(params)//
                .build()//
                .execute(stringCallback);`

调用时

` OkHttpRequestUtils.SINGLEOKHTTPREQUESTUTILS.uploadFile("upload", new MyResultCallback<String>() {
                    @Override
                    public void onError(Call call, Exception e) {
                        Log.i("test", "onError: " + e);
                    }

                    @Override
                    public void onResponse(String s) {
                        Log.i("test", "onResponse: " + s);
                    }
                });`

服务器可以接收到上传的文件，但是回调 onError: java.io.IOException: request failed , reponse's code is : 404

**Comment by hongyangAndroid** [comment]
` .addFile("myfiles", "123465.jpg", file)//`

第一个参数对应服务端接收的key.

建议让服务端检查下代码，看看是不是哪一步出错了，需要跳转到错误页面，结果没有错误页返回的404。

**Comment by JerryJson** [comment]
好了，谢谢，是服务器那边处理的有问题
