### ISSUE TITLE
OkHttpUtils的cancelTag方法

### ISSUE THREAD

**Issue by JackRo** [hongyangAndroid/okhttp-utils#209]
我看到你那个README的说明文档中调用的是静态方法，然后源码里OkHttpUtils是实例方法，文档和源码对不上。感觉根据tag取消请求的方法可以改成静态方法，方便使用。

**Comment by hongyangAndroid** [comment]
恩，感谢反馈，目前调用为：

```
OkHttpUtils.getInstance().cancelTag();
```

后面会添加静态方法。
