### ISSUE TITLE
您好，我想获取请求失败后的错误信息和响应码

### ISSUE THREAD

**Issue by Armyoftheworld** [hongyangAndroid/okhttp-utils#226]
您好，请问怎么获取请求失败后的具体错误信息和响应码，因为可能会根据不同的错误信息进行相应的操作？

**Comment by hongyangAndroid** [comment]
```
class MyCallBack extends Callback<String>
    {
        @Override
        public boolean validateReponse(Response response, int id)
        {
            return true;
        }

        @Override
        public String parseNetworkResponse(Response response, int id) throws Exception
        {
            int code = response.code();
            
            //根据code，解析数据
            return null;
        }

        @Override
        public void onError(Call call, Exception e, int id)
        {

        }

        @Override
        public void onResponse(String response, int id)
        {

        }
    }
```

**Comment by Armyoftheworld** [comment]
哦，原来是这样，我之前一直想着怎么在onError里面获取的，谢谢鸿神

**Comment by LQG24** [comment]
原来除了加    @Override
        public String parseNetworkResponse(Response response, int id) throws Exception
        {
            int code = response.code();

            //根据code，解析数据
            return null;
        }
这个方法之外还得加
   @Override
        public boolean validateReponse(Response response, int id)
        {
            return true;
        }

**Comment by yulinwoniu** [comment]
通过     public String parseNetworkResponse(Response response, int id) throws Exception
        {
            int code = response.code();

            //根据code，解析数据
            return null;
        }
这个方法拿到的响应码不是0就是200啊

**Comment by yulinwoniu** [comment]
OK    @Override
        public boolean validateReponse(Response response, int id)
        {
            return true;
        }
没有加这个方法
