### ISSUE TITLE
crash-没加空指针保护

### ISSUE THREAD

**Issue by typ0520** [hongyangAndroid/okhttp-utils#237]
threadid=17: thread exiting with uncaught exception (group=0xa6287288)
06-20 09:29:15.787 25723-25777/com.dx168.epmyg W/System.err: java.lang.NullPointerException
06-20 09:29:15.787 25723-25777/com.dx168.epmyg W/System.err:     at com.zhy.http.okhttp.cookie.store.MemoryCookieStore.add(MemoryCookieStore.java:25)
06-20 09:29:15.787 25723-25777/com.dx168.epmyg W/System.err:     at com.zhy.http.okhttp.cookie.CookieJarImpl.saveFromResponse(CookieJarImpl.java:29)
06-20 09:29:15.787 25723-25777/com.dx168.epmyg W/System.err:     at okhttp3.internal.http.HttpEngine.receiveHeaders(HttpEngine.java:866)
06-20 09:29:15.787 25723-25777/com.dx168.epmyg W/System.err:     at okhttp3.internal.http.HttpEngine.readResponse(HttpEngine.java:598)
06-20 09:29:15.787 25723-25777/com.dx168.epmyg W/System.err:     at okhttp3.RealCall.getResponse(RealCall.java:241)
06-20 09:29:15.787 25723-25777/com.dx168.epmyg W/System.err:     at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:198)
06-20 09:29:15.787 25723-25777/com.dx168.epmyg W/System.err:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:160)
06-20 09:29:15.787 25723-25777/com.dx168.epmyg W/System.err:     at okhttp3.RealCall.access$100(RealCall.java:30)
06-20 09:29:15.787 25723-25777/com.dx168.epmyg W/System.err:     at okhttp3.RealCall$AsyncCall.execute(RealCall.java:127)
06-20 09:29:15.787 25723-25777/com.dx168.epmyg W/System.err:     at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
06-20 09:29:15.787 25723-25777/com.dx168.epmyg W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
06-20 09:29:15.787 25723-25777/com.dx168.epmyg W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
06-20 09:29:15.787 25723-25777/com.dx168.epmyg W/System.err:     at java.lang.Thread.run(Thread.java:856)

**Comment by hongyangAndroid** [comment]
请问使用的版本是？log上看并非是最新版本~

**Comment by typ0520** [comment]
我用的是2.4.1，我看最新的代码是在22行(
okhttp-utils/okhttputils/src/main/java/com/zhy/http/okhttp/cookie/store/MemoryCookieStore.java),
`List<Cookie> oldCookies = allCookies.get(url.host());` ,oldCookies没做空指针判断，方便修改下发布个新版本吗，急着上线，你要是没时间我就自己改掉源码依赖了 呜呜。。。。

**Comment by hongyangAndroid** [comment]
十分钟后更新新版本，不过2.4.1和目前版本用法上有少许的差异~ 你可以看下readme

**Comment by typ0520** [comment]
好的，谢谢你哈
