### ISSUE TITLE
maven 报错，怎么修改插件地址apply plugin: 'com.github.dcendents.android-maven'

### ISSUE THREAD

**Issue by Larnoo** [hongyangAndroid/okhttp-utils#24]
Error:(2, 0) Cause: org/gradle/api/publication/maven/internal/DefaultMavenFactory
<a href="openFile:F:\larno\okhttp-utils\okhttputils\build.gradle">Open File</a>

**Comment by yiyi99** [comment]
版本高了，把build.gradle中classpath 'com.github.dcendents:android-maven-plugin:1.2'改成classpath 'com.github.dcendents:android-maven-gradle-plugin:1.3'

**Comment by yangxyjd** [comment]
改成classpath 'com.github.dcendents:android-maven-gradle-plugin:1.3'之后:

Error:Could not find com.github.dcendents:android-maven-plugin:1.3.
Searched in the following locations:
    file:/D:/Program Files/Android/Android Studio/gradle/m2repository/com/github/dcendents/android-maven-plugin/1.3/android-maven-plugin-1.3.pom
    file:/D:/Program Files/Android/Android Studio/gradle/m2repository/com/github/dcendents/android-maven-plugin/1.3/android-maven-plugin-1.3.jar
    https://jcenter.bintray.com/com/github/dcendents/android-maven-plugin/1.3/android-maven-plugin-1.3.pom
    https://jcenter.bintray.com/com/github/dcendents/android-maven-plugin/1.3/android-maven-plugin-1.3.jar
Required by:
    :okhttp-utils:unspecified

**Comment by hongyangAndroid** [comment]
可以选择删除所有不需要的，留下：

```
apply plugin: 'com.android.library'

android{}

dependencies{}
```

即可。
