### ISSUE TITLE
Response response 如何获取IO流

### ISSUE THREAD

**Issue by ouacyou** [hongyangAndroid/okhttp-utils#25]
如何回调返回结果类型inputStream?

**Comment by hongyangAndroid** [comment]
目前最新版本支持自定义Callback，可以在parseNetworkResponse拿到response自己解析，
public abstract class AnyCallback extends Callback<?>
{
    //非UI线程，支持任何耗时操作
    @Override
    public User parseNetworkResponse(Response response) throws IOException
    {
        InputStream is = response.body().byteStream();
      
    }
}
