### ISSUE TITLE
上传文件提示 413

### ISSUE THREAD

**Issue by WoKee** [hongyangAndroid/okhttp-utils#254]
Response{protocol=http/1.1, code=413, message=Request Entity Too Large, url=http://api.develop.corp.com/uploadfiles}

**Comment by andyxialm** [comment]
@WoKee 如何解决的？

**Comment by ghyzx** [comment]
我也遇到413，不知神马情况
java.io.IOException: request failed , reponse's code is : 413

**Comment by ghyzx** [comment]
已解决，413是服务端认为所上传文件过大而拒绝，服务端解除限制 或者 将上传文件压缩一下（传小文件）即可
