### ISSUE TITLE
okhttp ＋ volley

### ISSUE THREAD

**Issue by guoyoujin** [hongyangAndroid/okhttp-utils#3]
我最近在做一个okhttp＋volley这样可以使用https加密协议，不知道你有什么好的建议哈，

**Comment by hongyangAndroid** [comment]
建议完全去除volley。

**Comment by guoyoujin** [comment]
@hongyangAndroid 为什么呢

**Comment by hongyangAndroid** [comment]
不好意思哈，之前算开个玩笑，关于二者整合可以参考：https://gist.github.com/JakeWharton/5616899 。 关于https加密这块，okhttp默认支持https，不过对于自签名的证书并不能支持，你可以参考我在辅助类里面写支持验证个人证书以及双向验证的部分。

**Comment by hush881025** [comment]
自签名的证书有什么实质上的用处吗？以前都没有用到这一块

**Comment by guoyoujin** [comment]
@hush881025 ,非常有用啊，如果你的服务器握手的时候需要自己的签名验证，那你只有加上服务器给你的签名文件进行验证，服务器才会返回数据给你，否则即时对方通过抓包软件，抓取到了你的https地址进行反问，但是他没有签名证书，所以无法通过验证，服务器就会拒绝他的访问，他也就没办法偷取你的数据了，这个应该是未来的方向，早点上手更好，有机会一起学习研究吧
