### ISSUE TITLE
如何打印request的body出来?

### ISSUE THREAD

**Issue by 494928699** [hongyangAndroid/okhttp-utils#38]
Request request =
        new Request.Builder().url(url).tag(url).post(MultipartBuilder.build()).build();

我使用这种方式请求，有办法打印出  request 的body吗？

**Comment by hongyangAndroid** [comment]
目前添加debug模式打印requestbody的，不过只针对text,json,xml等，MultipartBuilder这种方式可能上传的是文件，打印也是无意义的字符串。
