### ISSUE TITLE
Https请求,但是不需要证书,应该怎么去做

### ISSUE THREAD

**Issue by djw576981748** [hongyangAndroid/okhttp-utils#39]
Https请求,但是不需要证书,应该怎么去实现

**Comment by soyoungboy** [comment]
信任所有证书，百度下，应该能找到对应方法，先看下翔哥博客

**Comment by djw576981748** [comment]
已经搞定 谢谢
代码为
/**
     * 设置HTTPS请求验证
     * */
    private class MyHostnameVerifier implements HostnameVerifier {
        @Override
        public boolean verify(String hostname, SSLSession session) {
            // TODO Auto-generated method stub
            return true;
        }
    }
    private class MyTrustManager implements X509TrustManager {
        @Override
        public void checkClientTrusted(X509Certificate[] chain, String authType)
                throws CertificateException {
            // TODO Auto-generated method stub
        }
        @Override
        public void checkServerTrusted(X509Certificate[] chain, String authType)
                throws CertificateException {
            // TODO Auto-generated method stub
        }
        @Override
        public X509Certificate[] getAcceptedIssuers() {
            // TODO Auto-generated method stub
            return null;
        }
    }
