### ISSUE TITLE
content()传json为空

### ISSUE THREAD

**Issue by djw576981748** [hongyangAndroid/okhttp-utils#40]
new OkHttpRequest.Builder().url("https请求").content(json.toString()).post(new ResultCallback<String>() {}
请求是https请求,SSL认证代码已经写好了,json形式post请求
但是有时候传参为空,有时候传参有值.但是Log日志打印全部都是有值的.请问什么情况,怎么解决呢?

**Comment by djw576981748** [comment]
刚刚测试感觉应该是okhttp做了缓存处理,在一定事件内连续请求就失败,请问如何解决呢

**Comment by djw576981748** [comment]
我用OKHTTP的代码去写 没有任何问题 ,但是大神你的就是有问题的

**Comment by hongyangAndroid** [comment]
那你就核对下两种方式的代码流程，看看哪里不同，指出问题多好。
