### ISSUE TITLE
ImageUtils获取图像期待的高度 的问题

### ISSUE THREAD

**Issue by BigManing** [hongyangAndroid/okhttp-utils#43]
ImageUtils类 

private static int getExpectHeight(View view)
    {

        int height = 0;
        if (view == null) return 0;

        final ViewGroup.LayoutParams params = view.getLayoutParams();
        //如果是WRAP_CONTENT，此时图片还没加载，getWidth根本无效
        if (params != null && params.height != ViewGroup.LayoutParams.WRAP_CONTENT)
        {
            height = view.getWidth(); // 获得实际的宽度|=====？？？？？？？？？=========|
        }
       .........................
      return height;
    }

？号的 地方     我期待的高度    你获取的是宽度吧

**Comment by hongyangAndroid** [comment]
多谢指出！
