### ISSUE TITLE
下载时, onBefore()不回调

### ISSUE THREAD

**Issue by weinierfei** [hongyangAndroid/okhttp-utils#46]
翔哥,demo中,下载的时候,onBefore不回调啊

**Comment by hongyangAndroid** [comment]
demo里面下载的回调没有复写onBefore，你自己复写即可。

```
OkHttpUtils//
                .get()//
                .url(url)//
                .build()//
                .execute(new FileCallBack(Environment.getExternalStorageDirectory().getAbsolutePath(), "gson-2.2.1.jar")//
                {

                    @Override
                    public void onBefore(Request request)
                    {
                        super.onBefore(request);
                    }

                    @Override
                    public void inProgress(float progress)
                    {
                        mProgressBar.setProgress((int) (100 * progress));
                    }

                    @Override
                    public void onError(Request request, Exception e)
                    {
                        Log.e(TAG, "onError :" + e.getMessage());
                    }

                    @Override
                    public void onResponse(File file)
                    {
                        Log.e(TAG, "onResponse :" + file.getAbsolutePath());
                    }
                });
```

**Comment by weinierfei** [comment]
OkHttpUtil.downloadFile(url, "mnt/sdcard/Allinmd", "shipin.mp4", new ResultCallback<String>() {

            @Override
            public void onBefore(Request request) {
                super.onBefore(request);
               
                    LogUtil.e(TAG, "下载之前..." + request.body().contentLength());
                
            }

            @Override
            public void onError(Request request, Exception e) {
                LogUtil.e(TAG, "下载错误=" + e.getMessage());

            }

            @Override
            public void onResponse(String response) {
                LogUtil.i(TAG, "响应=" + response);
            }

            @Override
            public void inProgress(float progress) {
                super.inProgress(progress);
                LogUtil.i(TAG, "进度=" + progress);
            }

            @Override
            public void onAfter() {
                super.onAfter();
                LogUtil.i(TAG, "下载完成后.....");
            }

        });


我这么写不对吗?onBefore不执行啊

**Comment by hongyangAndroid** [comment]
代码已经更新了，参考下我上面的回复。
