### ISSUE TITLE
ResultCallback为啥要设计成这样？

### ISSUE THREAD

**Issue by JackRo** [hongyangAndroid/okhttp-utils#48]
new OkHttpRequest.Builder()
                .url(url)
                .destFileDir(Environment.getExternalStorageDirectory().getAbsolutePath())
                .destFileName("gson-2.2.1.jar")
                .download(new ResultCallback() {
                    @Override
                    public void onError(Request request, Exception e) {

                    }

                    @Override
                    public void onResponse(Object o) {

                    }
                });
这里我这样传参数就要报错“Missing type parameter.”，为啥不把ResultCallback里的onBefore、onAfter和inProgress抽象出来呢？

**Comment by hongyangAndroid** [comment]
目前对于Callback重构了，提供了`StringCallback`，`FileCallback`，`BitmapCallback`，当然也可以自定义Callback自己去解析。 对于onBefore , onAfter , onProgress几个方法，因为大多数的请求可能不关注这几个回调，所以就默认空实现了，有需要复写即可。
