### ISSUE TITLE
new OkHttpRequest.Builder().files添加文件的时候，为什么服务器获取不到

### ISSUE THREAD

**Issue by excellenttank** [hongyangAndroid/okhttp-utils#56]
new OkHttpRequest.Builder()
    .url(url)
    .params(params)
    .headers(headers)
    .tag(tag)
    .files(files)
    .upload(callback);这个地方的用法是我理解错了吗？
Pair<String, File> pair = new Pair("new_image", savedFile);将这个files放进去

**Comment by hongyangAndroid** [comment]
用法已经更新为：

```java
OkHttpUtils.post()//
    .addFile("mFile", "messenger_01.png", file)//
    .addFile("mFile", "test1.txt", file2)//
    .url(url)
    .params(params)//
    .headers(headers)//
    .build()//
    .execute(new MyStringCallback());
```

上述addFile3个参数，参数1为key，参数2为服务端接收到的文件名，参数3为file

参数1，相当于web表单中文件域中的name属性。

**Comment by excellenttank** [comment]
恩，我也看了，你新的写法，但是要改得改好多地方，之前的地方怎么才能正常上传呢，能帮忙指导一下吗

**Comment by flyou** [comment]
我用以前的版本也碰到了这个问题，多文件上传时超过6个文件有时候会出现异常，而且频率还不低。可是用新版本不定数目文件上传不好实现
