### ISSUE TITLE
升级okhttp3.0后的代码cookie不能保持

### ISSUE THREAD

**Issue by soyoungboy** [hongyangAndroid/okhttp-utils#65]
升级okhttp3.0后的代码cookie不能保持，原来2.7的时候还行（可能和最近合并的代码有关系）

**Comment by AnswerZhao** [comment]
遇到同样的问题，cookie无法保存，okhttp3.0，求鸿洋大神解决，急求

**Comment by LinLshare** [comment]
`        mHttpClient = new OkHttpClient.Builder().cookieJar(new CookieJar() {
            private final HashMap<String, List<Cookie>> cookieStore = new HashMap<>();
            //MD,終於把Cookie帶過去了，這裡key必須是String啊！！！！！！！！！！！！
            @Override
            public void saveFromResponse(HttpUrl url, List<Cookie> cookies) {
                cookieStore.put(url.host(), cookies);
            }
            @Override
            public List<Cookie> loadForRequest(HttpUrl url) {
                List<Cookie> cookies = cookieStore.get(url.host());
                return cookies != null ? cookies : new ArrayList<Cookie>();
            }
        }).build();`
