### ISSUE TITLE
Get 请求 缺少方法

### ISSUE THREAD

**Issue by jackTang11** [hongyangAndroid/okhttp-utils#7]
大神在get中补充一个方法 加参数吧  目前的get只是url  如果我要在其后加参数 肿么办,求补充

**Comment by hongyangAndroid** [comment]
Get请求，参数直接拼接到url后面就可以了。

**Comment by jackTang11** [comment]
这样感觉还是不好,能不能用一个map,或者集合,像asynchttp 那样,肯定有用户喜欢,如果单纯的再后面加,反而不好维护,乱

**Comment by hongyangAndroid** [comment]
恩，那可以考虑自己添加及扩展。
