### ISSUE TITLE
不支持手写url get参数。

### ISSUE THREAD

**Issue by WeissWill** [hongyangAndroid/okhttp-utils#74]
如下不返回数据。之前用AsyncHttpClient是支持的
String url ="http://.../mobile/index.php?act=goods&op=goods_list";
 OkHttpUtils
                    .get()
                    .url(url)
                    .addParams("page","10")
                    .build()
                    .execute(new StringCallback()
改成如下才返回
            String url =".../mobile/index.php";
            OkHttpUtils
                    .get()
                    .url(url)
                    .addParams("act","goods")
                    .addParams("op","goods_list")
                    .addParams("page","10")
                    .build()
                    .execute(new StringCallback()
大神有没办法封装一下。

**Comment by hongyangAndroid** [comment]
现已经支持。
