### ISSUE TITLE
get请求多次后response.code()就一直400

### ISSUE THREAD

**Issue by Mrmumu** [hongyangAndroid/okhttp-utils#82]
ist下拉刷新，刷新十几次后，response.code()就一直400，必须要重启软件才能正常请求。我用原始的okhttp进行操作就不会有这个问题。您知道大概的原因吗？或者是猜测？

**Comment by Mrmumu** [comment]
这个问题解决了，我将OKHttpUtils中的okHttpClientBuilder.cookieJar(new SimpleCookieJar());注释掉了，然后就没问题。但是我还是不清楚这是为什么?

**Comment by hongyangAndroid** [comment]
你好，多谢反馈，抱歉这么久回复。
这个400的问题应该是由于cookie设置过多导致的，关于这个的解决，我对SimpleCookieJar做了下处理，去除了保存重复的cookie的问题。
