### ISSUE TITLE
特殊场景有问题:OkHttpUtils.post().url(str).build().execute();

### ISSUE THREAD

**Issue by lishifeng** [hongyangAndroid/okhttp-utils#89]
**请求默认会添加一个Body。name 是1 .值也是1。**
使用场景：
OkHttpUtils.post().url(str).build().execute()；
当所有的请求包括参数都在str里面，并通过加密key加密后生成的链接）如果多了一个参数，那么服务端提示加密错误。
解决方案OkHttpUtils.post().url(str).addParams("", "").build().execute();
问题出在PostFormRequest类
addParams  133行。
     if (params == null || params.isEmpty())
        {
            builder.add("1", "1");
            return;
        }

**Comment by hongyangAndroid** [comment]
多谢指出，已经修复。
