### ISSUE TITLE
封装的同步的Post每次都报阻碍主线程

### ISSUE THREAD

**Issue by hulegithub** [hongyangAndroid/okhttp-utils#9]
每次这里都会报阻碍主线程，我要怎么在工具类里处理呢，异步的postAsyn（）就可以，求指点。
  /**
         * 同步的Post请求:直接将bodyStr以写入请求体
         */
        public Response post(String url, String bodyStr) throws IOException {
            RequestBody body = RequestBody.create(MEDIA_TYPE_STRING, bodyStr);
            Request request = buildPostRequest(url, body);
            Response response = mOkHttpClient.newCall(request).execute();//这里
            return response;
        }

**Comment by hongyangAndroid** [comment]
同步的方法本身就会阻塞当前线程，如果希望不阻塞当前线程，选择提供的异步的方法，比如postAysn之类的。
